version: 2

jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/laravel
    steps:
#      - checkout
#      - run: sudo apt install -y libsqlite3-dev
#      - run: sudo composer self-update
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.json" }}
#            - composer-v1-
#      - run: composer install -n --prefer-dist
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.json" }}
#          paths:
#            - vendor
#      - run: touch storage/testing.sqlite
#      - run: php artisan migrate --env=testing --database=sqlite_testing --force
#      - run: ./vendor/bin/codecept build
#      - run: ./vendor/bin/codecept run
      - add_ssh_keys:
          fingerprints:
            - "35:92:e8:23:90:f1:af:06:e6:cd:98:99:ab:6f:c5:58"
      - deploy:
          command: |
              echo 'dev.pagomio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDicB90BzIGbNe2EaeOYdPJ0jwFzGvRDBWXXMzjTmfHk10ig+g1u+8EF5qDzA9iZEudUq1maSss05lAIXvgBqGchX3QiuNPFEmK4q/l09tfK3sVZStiJ25j5c3is6DmdLgaMXleTFdV4W/eG39vogQ0w1ZBHqkn/0EfZMjVjiQHI901pHL3tgo6PX3DwpV6kHiDDKHV1MADGeSh2xJD/Es11zDNOQ5lHu6N3HEJYO8xSzvYAzOCULbZkI/Ym+ZKQ0ZQNtCndWm5laHbH6tkJf4a5QLR9xAFGSdBXKVZDy4lvBdUOGENBqSuPhRniR4I5EpxytZNpKiGTLPjg4WRKS6mjZ6zh5kXUzvG2SjtaMVQVXH3gs1gFfGIYs2LhF5UwQ6Wcgo31N5VzMQyAf8nQnvMsaOGZCoU+AQZoDR4amki+dX3RK25VefE3Ul7Um2WP+zl+Tn16/6VCUKyyfGS7PfH1IQOaHm8RyQqoN11RWtYaDoxkuc6O1+Rb6r0S1al0F+VQgq0NRH57LA3vU8DBh2CnLUmRsaiTKafKNEqnJqxrhAe7w5CFHdnFN6/57F+rWxKrlYzTU1f1ESaf6iQ7tc75gPx03PxO0NuEjNN7vIoRS7z2+pfg8QIeHqU+bbaf3XK62NG4mR6mtk7Lcud/sxbFcDIR/PnLAmZlJnzJN1tfw==' >> ~/.ssh/known_hosts
              ssh -v josorio@dev.pagomio.com 'echo "Hola" >> test.txt'
